{{- if .Values.tilerServer.enabled -}}
{{ if eq .Values.tilerServer.env.TILER_CACHE_TYPE "s3" }}
{{- if .Values.tilerServerCacheCleaner.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-tiler-server-cache-cleaner
  labels:
    app: {{ template "osm-seed.name" . }}
    component: tiler-server-cache-cleaner
    environment: {{ .Values.environment }}
    release: {{ .Release.Name }}
spec:
  replicas: {{ .Values.tilerServerCacheCleaner.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "osm-seed.name" . }}
  template:
    metadata:
      labels:
        app: {{ template "osm-seed.name" . }}
    spec:
      containers:
        - name: {{ .Release.Name }}-tiler-server-cache-cleaner-deployment
          image: {{ .Values.tilerServer.image.name }}:{{ .Values.tilerServer.image.tag }}
          command: [{{.Values.tilerServerCacheCleaner.command}}]
          {{- if .Values.tilerServerCacheCleaner.resources.enabled }}
          resources:
            requests:
              memory: {{ .Values.tilerServerCacheCleaner.resources.requests.memory }}
              cpu: {{ .Values.tilerServerCacheCleaner.resources.requests.cpu }}
            limits:
              memory: {{ .Values.tilerServerCacheCleaner.resources.limits.memory }}
              cpu: {{ .Values.tilerServerCacheCleaner.resources.limits.cpu }}
          {{- end }}
          envFrom:
          - configMapRef:
              name: {{ .Release.Name }}-tiler-server-cm
      {{- if .Values.tilerServerCacheCleaner.nodeSelector.enabled }}
      nodeSelector:
        {{ .Values.tilerServerCacheCleaner.nodeSelector.label_key }} : {{ .Values.tilerServerCacheCleaner.nodeSelector.label_value }}
      {{- end }}
{{- end }}
{{- end }}
{{- end }}