{{- if .Values.tilerServer.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-tiler-server-cm
data:
    POSTGRES_HOST: {{ .Release.Name }}-tiler-db
    POSTGRES_DB: {{ .Values.tilerDb.env.POSTGRES_DB | quote }}
    POSTGRES_PASSWORD: {{ .Values.tilerDb.env.POSTGRES_PASSWORD | quote }}
    POSTGRES_USER: {{ .Values.tilerDb.env.POSTGRES_USER | quote }}
    POSTGRES_PORT: {{ .Values.tilerDb.env.POSTGRES_PORT | quote }}
    TILER_SERVER_PORT: {{ .Values.tilerServer.env.TILER_SERVER_PORT | quote }}
    TILER_CACHE_TYPE: {{ .Values.tilerServer.env.TILER_CACHE_TYPE | quote }}
    TILER_CACHE_REGION: {{ .Values.tilerServer.env.TILER_CACHE_REGION | quote }}
    TILER_CACHE_BUCKET: {{ .Values.tilerServer.env.TILER_CACHE_BUCKET | quote }}
    TILER_CACHE_BASEPATH: {{ .Values.tilerServer.env.TILER_CACHE_BASEPATH | quote }}
    TILER_CACHE_AWS_ACCESS_KEY_ID: {{ .Values.tilerServer.env.TILER_CACHE_AWS_ACCESS_KEY_ID | quote }}
    TILER_CACHE_AWS_SECRET_ACCESS_KEY: {{ .Values.tilerServer.env.TILER_CACHE_AWS_SECRET_ACCESS_KEY | quote }}
    TILER_CACHE_MAX_ZOOM: {{ .Values.tilerServer.env.TILER_CACHE_MAX_ZOOM | quote }}
    EXECUTE_REINDEX: {{ .Values.tilerServer.env.EXECUTE_REINDEX | default "false" | quote }}
    EXECUTE_VACUUM_ANALYZE: {{ .Values.tilerServer.env.EXECUTE_VACUUM_ANALYZE | default "false" | quote }}
    CLOUDPROVIDER: {{ .Values.cloudProvider | quote }}
    {{- if eq .Values.cloudProvider "aws" }}
    AWS_S3_BUCKET: {{ .Values.AWS_S3_BUCKET | quote }}
    {{- end }}
    {{- if eq .Values.cloudProvider "gcp" }}
    GCP_STORAGE_BUCKET: {{ .Values.GCP_STORAGE_BUCKET | quote }}
    {{- end }}
{{- end }}