{{- if .Values.tmApi.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-tasking-manager-api 
  labels:
    app: {{ template "osm-seed.name" . }}
    component: tasking-manager-api-deployment
    environment: {{ .Values.environment }}
    release: {{ .Release.Name }}
spec:
  replicas: {{ .Values.tmApi.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "osm-seed.name" . }}
      release: {{ .Release.Name }}
      run: {{ .Release.Name }}-tasking-manager-api
  template:
    metadata:
      labels:
        app: {{ template "osm-seed.name" . }}
        release: {{ .Release.Name }}
        run: {{ .Release.Name }}-tasking-manager-api
    spec:
      containers:
        - name: {{ .Chart.Name }}-tasking-manager-api
          image: "{{ .Values.tmApi.image.name }}:{{ .Values.tmApi.image.tag }}"
          ports:
            - name: http
              containerPort: 5000
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: 5000
            initialDelaySeconds: 120
            timeoutSeconds: 30
          {{- if .Values.tmApi.resources.enabled }}
          resources:
            requests:
              memory: {{ .Values.tmApi.resources.requests.memory }}
              cpu: {{ .Values.tmApi.resources.requests.cpu }}
            limits:
              memory: {{ .Values.tmApi.resources.limits.memory }}
              cpu: {{ .Values.tmApi.resources.limits.cpu }}
          {{- end }}
          envFrom:
          - configMapRef:
              name: {{ .Release.Name }}-tm-common-env

      {{- if .Values.tmApi.nodeSelector.enabled }}
      nodeSelector:
        {{ .Values.tmApi.nodeSelector.label_key }} : {{ .Values.tmApi.nodeSelector.label_value }}
      {{- end }}
{{- end }}