{{- if .Values.web.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "osm-seed.fullname" . }}-web
  labels:
    app: {{ template "osm-seed.name" . }}
    component: web-deployment
    environment: {{ .Values.environment }}
    release: {{ .Release.Name }}
spec:
  replicas: {{ .Values.web.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "osm-seed.name" . }}
      release: {{ .Release.Name }}
      run: {{ .Release.Name }}-web
  template:
    metadata:
      labels:
        app: {{ template "osm-seed.name" . }}
        release: {{ .Release.Name }}
        run: {{ .Release.Name }}-web
    spec:
      containers:
        - name: {{ .Chart.Name }}-web
          image: "{{ .Values.web.image.name }}:{{ .Values.web.image.tag }}"
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            {{- if .Values.web.livenessProbeExec }}
            exec:
              command:
              - /bin/bash
              - -c
              - ./liveness.sh
            initialDelaySeconds: 600
            timeoutSeconds: 5
            periodSeconds: 10
            failureThreshold: 3
            {{- else }}
            httpGet:
              path: /api/0.6/capabilities
              port: 80
            initialDelaySeconds: 600 # 10 min, because the compile process takes time.
            timeoutSeconds: 30
            {{- end }}
          {{- if .Values.web.resources.enabled }}
          resources:
            requests:
              memory: {{ .Values.web.resources.requests.memory }}
              cpu: {{ .Values.web.resources.requests.cpu }}
            limits:
              memory: {{ .Values.web.resources.limits.memory }}
              cpu: {{ .Values.web.resources.limits.cpu }}
          {{- end }}
          env:
            - name: GET_HOSTS_FROM
              value: dns
            - name: POSTGRES_HOST
              value: {{ .Release.Name }}-db # This should give us the host for DB on the cluster.
            - name: POSTGRES_DB
              value: {{ .Values.db.env.POSTGRES_DB }}
            - name: POSTGRES_PASSWORD
              value: {{ quote .Values.db.env.POSTGRES_PASSWORD }}
            - name: POSTGRES_USER
              value: {{ .Values.db.env.POSTGRES_USER }}
            - name: MAILER_ADDRESS
              value: {{ .Values.web.env.MAILER_ADDRESS }}
            - name: MAILER_DOMAIN
              value: {{ .Values.web.env.MAILER_DOMAIN }}
            - name: MAILER_USERNAME
              value: {{ .Values.web.env.MAILER_USERNAME }}
            - name: MAILER_PASSWORD
              value: {{ quote .Values.web.env.MAILER_PASSWORD }}
            - name: MAILER_FROM
              value: {{ .Values.web.env.MAILER_FROM }}
            - name: MAILER_PORT
              value: {{ .Values.web.env.MAILER_PORT | default "25" | quote }}
            - name: OPENSTREETMAP_id_key
              value: {{ .Values.web.env.OSM_id_key }}
            - name: OAUTH_CLIENT_ID
              value: {{ .Values.web.env.OAUTH_CLIENT_ID }}
            - name: OAUTH_KEY
              value: {{ .Values.web.env.OAUTH_KEY }}
            - name: OPENSTREETMAP_memcache_servers
              value: {{ .Release.Name }}-memcached:11211
              # Set SERVER_URL in case we use ingress
              {{- if eq .Values.serviceType "ClusterIP" }}
            - name: SERVER_URL
              {{- if .Values.web.ingressDomain }}
              value: {{ .Values.web.ingressDomain }}
              {{- else }}
              value: {{ .Values.domain }}
              {{- end }}
            - name: SERVER_PROTOCOL
              value : "https"
              {{- end }}
              # Set SERVER_URL in case we use LoadBalancer
              {{- if eq .Values.serviceType "LoadBalancer" }}
            - name: SERVER_URL
              value: {{ .Values.domain }}
            - name: SERVER_PROTOCOL
              value : "https"
              {{- end }}
              # Set SERVER_URL in case we use NodePort
              {{- if eq .Values.serviceType "NodePort" }}
            - name: SERVER_URL
              value: dns
            - name: SERVER_PROTOCOL
              value : http
              {{- end }}
              # Nominatim domain
            - name: NOMINATIM_URL
              value: {{ .Values.web.env.NOMINATIM_URL }}
              # Nominatim domain
            - name: OVERPASS_URL
              value: {{ .Values.web.env.OVERPASS_URL }}
            # Here can be added other Env variables for monitoring, debugging, etc.
            - name: NEW_RELIC_LICENSE_KEY
              value: {{ .Values.web.env.NEW_RELIC_LICENSE_KEY | default ""}}
            - name: NEW_RELIC_APP_NAME
              value: {{ .Values.web.env.NEW_RELIC_APP_NAME | default ""}}
            - name: ORGANIZATION_NAME
              value: {{ .Values.web.env.ORGANIZATION_NAME | default "OpenStreetMap"}}
            - name: WEBSITE_STATUS
              value: {{ .Values.web.env.WEBSITE_STATUS | default "online"}}
            - name: API_TIMEOUT
              value: {{ .Values.web.env.API_TIMEOUT | default "30" | quote }}
            - name: WEB_TIMEOUT
              value: {{ .Values.web.env.WEB_TIMEOUT | default "30" | quote }}
            # This parameter is specifically if you want to restore a any backup to db, 
            # you done need to set this values.yaml in case you don't use
            - name: BACKUP_FILE_URL
              value: {{ .Values.web.env.BACKUP_FILE_URL | default "none" | quote }}
            - name: RAILS_CREDENTIALS_YML_ENC
              value: {{ .Values.web.env.RAILS_CREDENTIALS_YML_ENC | quote }}
            - name: RAILS_MASTER_KEY
              value: {{ .Values.web.env.RAILS_MASTER_KEY | quote }}
            - name: RAILS_ENV
              value: {{ .Values.web.env.RAILS_ENV | quote }}
            - name: RAILS_LOG_LEVEL
              value: {{ .Values.web.env.RAILS_LOG_LEVEL | default "info" | quote }}
            - name: RAILS_STORAGE_SERVICE
              value: {{ .Values.web.env.RAILS_STORAGE_SERVICE | default "local" | quote }}
            - name: RAILS_STORAGE_REGION
              value: {{ .Values.web.env.RAILS_STORAGE_REGION | quote }}
            - name: RAILS_STORAGE_BUCKET
              value: {{ .Values.web.env.RAILS_STORAGE_BUCKET | quote }}
          volumeMounts:
            - mountPath: /dev/shm
              name: shared-memory
      volumes:
        - emptyDir:
            medium: Memory
            sizeLimit: {{ .Values.web.sharedMemorySize }}
          name: shared-memory
      {{- if .Values.web.nodeSelector.enabled }}
      nodeSelector:
        {{ .Values.web.nodeSelector.label_key }} : {{ .Values.web.nodeSelector.label_value }}
      {{- end }}
{{- end }}
